version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:1.25.4-alpine
    restart: always
    volumes:
      - ./html:/html
      - ./nginx_conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443


  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email ${DOMAIN_EMAIL} --force-renewal --agree-tos --no-eff-email -d ${DOMAIN_URL}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt


